### ISSUE TITLE
Custom filter function

### ISSUE THREAD

**Issue by HackedBeat** [Khan/react-multi-select#1]
I need the ability to set the custom function for searching, because _fuzzy-match-utils_ does not work with Cyrillic.
Please, add prop like _filterOptions_ in [react-select](https://github.com/JedWatson/react-select#filtering-options).

**Comment by BrianGenisio** [comment]
Thanks for the suggestion @HackedBeat.  You can now pass a `filterOptions` function property to the component as of 0.2.4.  The signature of your `filterOptions` function will look like this:

```
(options: Array<Option>, filter: string) => Array<Option>
```
