### ISSUE TITLE
Accessibility improvements suggestion & code

### ISSUE THREAD

**Issue by 7ruth** [Khan/react-multi-select#18]
Hello, this is an awesome dropdown library, exactly what I have been searching for a long time. Thank you for putting it together!

I see that there are already many accessibility features included, but may I add that most of keyboard-only users expect drop downs to open when they are in focus, by pressing ether space bar or enter (instead of key down as it's done right now). 

Reference link: https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/menubar/menubar-1/menubar-1.html#

Would you be so kind and update this block of code to also include space bar and enter?

In dropdown.js 

```_this.handleKeyDown = function (e) {
            switch (e.which) {
                case 27:
                    // Escape
                    _this.toggleExpanded(false);
                    break;
                case 38:
                    // Up Arrow
                    _this.toggleExpanded(false);
                    break;
                case 13: // Enter Key      <-----updated line
                case 32: // Space           <-----updated line
                case 40: // Down Arrow
                    _this.toggleExpanded(true);
                    break;
                default:
                    return;
            }```

**Comment by BrianGenisio** [comment]
Thanks for the suggestion.  Landed in 0.3.1
