### ISSUE TITLE
Webpack freaking out on react-tag-editor

### ISSUE THREAD

**Issue by mikepc** [Khan/react-multi-select#3]
./~/react-tag-editor/src/index.jsx
Module parse failed: /Users/x74f/vendor-portal-web/node_modules/react-tag-editor/src/index.jsx Unexpected token (124:9)
You may need an appropriate loader to handle this file type.
| 		var inputSize = Math.max(props.value? props.value.length: 0, this.props.minInputSize)
| 
| 		return <Field ref="field" {...props} inputProps={{size: inputSize}}/>
| 	},
|

I have triple-checked my babel loader and it *is* configured to handle JSX files. 

Any thoughts?

**Comment by Cuddl3s** [comment]
Hey, don't know if you already fixed it, but I had this error sometimes when I imported from the wrong package , eg a subpackage of the real package. My IDE sometimes did that... It's worth checking

**Comment by BrianGenisio** [comment]
I'm not sure what is going on here, but I don't believe it is related to this module.  If I am mistaken, and this is still a problem, I'm happy to re-open and engage more.
