### ISSUE TITLE
By default checked 

### ISSUE THREAD

**Issue by sweetyv** [Khan/react-multi-select#4]
Hi @BrianGenisio, 

Is there a way i can keep some of my items checked in the dropdown by default? I am passing data from server and i want to show some of them checked. Please help. Its urgent.

**Comment by HackedBeat** [comment]
Yes, you can. Something like this:

```javascript
...

render() {
	const options = [
		{ label: 'option1', value: 1 },
		{ label: 'option2', value: 2 },
		{ label: 'option3', value: 3 },
		{ label: 'option4', value: 4 },
	];
	const selected = [1, 2];
	
	return (
		<MultiSelect
		  options={options}
		  selected={selected}
		/>
	);
}

...
```

**Comment by sweetyv** [comment]
ohh nice. And what if we have to select all by default?

**Comment by HackedBeat** [comment]
Change 
```javascript 
const selected = [1, 2]; 
``` 

to

```javascript
const selected = options.map(({ value }) => value);
```

**Comment by sweetyv** [comment]
Its not working on my end. 
Below is my code. Could you please check and help ?

const categories = [
    {label: "Skincare", value: "Skincare"},
    {label: "Skincare - pharma", value: "Skincare - pharma"},
    {label: "Skincare - mass", value: "Skincare - mass"},
];

handleCategoriesChanged(selected) {
  let {filterValues} = this.state;
  filterValues.categories = selected;
  this.setState({
    filterValues
  }, this.props.allDropDownValues(filterValues));
}

Inside render()
` const allSelected = categories.map(({ value }) => value);`

```
<Dropdown
               options={categories}
                selected={allSelected}
               onSelectedChanged={this.handleCategoriesChanged.bind(this)}
             />
```

**Comment by HackedBeat** [comment]
@sweetyv What exactly does not work?
Did you try to store ```selected``` variable in ```state```?

**Comment by sweetyv** [comment]
Yes, have stored selected in state. 
The problem is when I open the dropdown all values are not selected.

**Comment by HackedBeat** [comment]
Can you create a gist with full code?

**Comment by sweetyv** [comment]
Please check:
https://gist.github.com/backhamza/b7655ff376989698a0c780b713bc7381

**Comment by HackedBeat** [comment]
@sweetyv Please, see my reply [there](https://gist.github.com/backhamza/699ad6da7161162ba303ff1b1a45d93d#gistcomment-2179873)

**Comment by sweetyv** [comment]
@HackedBeat were you able to check the code? Could you please help? I am not sure what could possible go wrong. 
https://gist.github.com/backhamza/b7655ff376989698a0c780b713bc7381

**Comment by CWolfAnderson** [comment]
Any luck with this issue? Perhaps an alternative module?

**Comment by HackedBeat** [comment]
@CWolfAnderson And what's the problem with using the [method mentioned above](https://github.com/Khan/react-multi-select/issues/4#issuecomment-323364483)?

**Comment by BrianGenisio** [comment]
I'm closing this.  I think @HackedBeat answered this properly and the gist shows that the wrapper wasn't sending the proper through.  LMK if I misunderstood, but I don't believe this is a bug.

**Comment by backhamza** [comment]
Hi, @HackedBeat 
I am trying to set 1 label selected by default but when I am writing, it's not showing one selected. Below is my code, can you please help me again. Thanks in advance.

`<li>
                <label>Trust Level</label>
                <Dropdown
                  options={benefit}
                  onSelectedChanged={this.handleBenefitChanged.bind(this)}
                  selected={this.state.filterValues.Benefits[1]}
                />
              </li>`


`const benefit = [
  {label: "High Trust", value: "High Trust"},
  {label: "Low Trust", value: "Low Trust"},
  {label: "Medium Trust", value: "Medium Trust"}
];`

**Comment by backhamza** [comment]
When I `log` this `this.state.filterValues.Benefits[1]` I am getting `Low Trust`.
