### ISSUE TITLE
Checkbox does not update visual checked style when clicked

### ISSUE THREAD

**Issue by mcgrathg** [Khan/react-multi-select#6]
When you click on the checkbox input in the dropdown, it does not visually update the checkmark until you move the mouse so that the checkbox is no longer hovered.

Occurs on https://khan.github.io/react-multi-select.

Demo: 
![react-multi-select bug](https://user-images.githubusercontent.com/5464892/35580720-d8a8542e-05b7-11e8-8a3f-04506522063b.gif)

**Comment by BrianGenisio** [comment]
Oh, wow!  Thanks for pointing this out.  I can't believe I never saw that.  I think I've clicked on the label for most of my testing.

I've fixed this in v0.2.5.  LMK if you have any further troubles!
